version: "3.4"
services:

  http_server:
    build: ./http_server
    network_mode: "host"
    environment:
      - HTTP_LISTEN_PORT
      - API_DB_PORT
      - API_DB_HOSTNAME
    # ports:
    #   - ${HTTP_LISTEN_PORT}:${HTTP_LISTEN_PORT}
    volumes:
      - ${HOST_PRIVATE_KEY_FILE}:/srv/host_private_key

  # jwt_generator:
  #   build: ./jwt_generator

  postgrest:
    build: ./postgrest
    network_mode: "host"
    expose:
      - ${API_DB_PORT}
    environment:
      - PGHOST
      - PGPORT
      - PGDB
      - API_PG_USER
      - API_PG_PASSWORD
      - API_DB_SCHEMA
      - API_ANON_ROLE
      - API_DB_POOL
      - API_DB_POOL_TIMEOUT
      - API_DB_PORT
      - HTTP_SERVER_HOSTNAME
    depends_on:
      - db
      - db_schema

  db:
    image: postgres:12.0-alpine
    network_mode: "host"
    expose:
      - ${PGPORT}
    environment:
      - PGHOST
      - PGUSER
      - PGPASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data

  db_schema:
    network_mode: "host"
    build: ./db_schema
    environment:
      - PGHOST
      - PGUSER
      - PGPASSWORD
    depends_on:
      - db
